### ISSUE TITLE
Segfault on launch

### ISSUE THREAD

**Issue by lgbaldoni** [Dudemanguy911/vmn#1]
Built 0.03 on openSUSE Tumbleweed and it crashes on startup.

**Comment by Dudemanguy** [comment]
I'm sure I've overlooked a lot of things, but it's nice that someone else is trying it out. Can you run it in gdb and give me the backtrace?

**Comment by lgbaldoni** [comment]
Sure
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7940ab4 in _IO_getc (fp=0x0) at getc.c:37
37        if (!_IO_need_lock (fp))
(gdb) bt
#0  0x00007ffff7940ab4 in _IO_getc (fp=0x0) at getc.c:37
#1  0x0000555555559f92 in read_cfg_file (cfg=cfg@entry=0x7fffffffd8f0, 
    cfg_file=cfg_file@entry=0x5555555c5910 "/home/user/.config/vmn/config") at ../src/config.c:540
#2  0x000055555555a22b in cfg_init (argc=1, argv=0x7fffffffdc68) at ../src/config.c:599
#3  0x00005555555576f1 in main (argc=1, argv=0x7fffffffdc68) at ../src/main.c:49
```

**Comment by Dudemanguy** [comment]
Yeah trying to read a config file that doesn't exist is dumb. Thanks for reporting this. 761c90411 should fix it.

**Comment by Dudemanguy** [comment]
Oh and I would recommend using the master branch anyway. The releases don't have much logic behind them.
